In [ ]:
import pandas as pd 
import matplotlib.pyplot as plt
import plotly.express as px

df = pd.read_csv("athlete_events.csv")

""" Tabell pÃ¥ antal medaljer per individ i tyskland """
ger_df = df[df["NOC"] == "GER"]
ger_df1 = pd.concat([ger_df,pd.get_dummies(df["Medal"])],axis = 1)
ger_indv_medals = ger_df1.groupby("NOC").sum()[["Gold","Silver","Bronze"]].sort_values("Gold",ascending=False).reset_index()
ger_df_wo_nan = ger_df.dropna(subset=["Medal"])
ger_df_wo_nan

# px.bar(ger_indv_medals[""])

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
261,133,Franz Abb,M,NaN,NaN,NaN,Germany,GER,1900 Summer,1900,Summer,Paris,Gymnastics,Gymnastics Men's Individual All-Around,NaN
669,389,Adolf Gaston Abel,M,45.0,NaN,NaN,Germany,GER,1928 Summer,1928,Summer,Amsterdam,Art Competitions,"Art Competitions Mixed Architecture, Designs F...",NaN
670,389,Adolf Gaston Abel,M,45.0,NaN,NaN,Germany,GER,1928 Summer,1928,Summer,Amsterdam,Art Competitions,"Art Competitions Mixed Architecture, Architect...",NaN
687,396,Katja Abel,F,25.0,165.0,55.0,Germany,GER,2008 Summer,2008,Summer,Beijing,Gymnastics,Gymnastics Women's Individual All-Around,NaN
688,396,Katja Abel,F,25.0,165.0,55.0,Germany,GER,2008 Summer,2008,Summer,Beijing,Gymnastics,Gymnastics Women's Team All-Around,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271022,135528,Marc Zwiebler,M,24.0,181.0,75.0,Germany,GER,2008 Summer,2008,Summer,Beijing,Badminton,Badminton Men's Singles,NaN
271023,135528,Marc Zwiebler,M,28.0,181.0,75.0,Germany,GER,2012 Summer,2012,Summer,London,Badminton,Badminton Men's Singles,NaN
271024,135528,Marc Zwiebler,M,32.0,181.0,75.0,Germany,GER,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Men's Singles,NaN
271026,135530,Philip Zwiener,M,23.0,202.0,98.0,Germany,GER,2008 Summer,2008,Summer,Beijing,Basketball,Basketball Men's Basketball,NaN
271027,135531,Sabine Beate Zwiener (-Jauchstetter),F,24.0,172.0,52.0,Germany,GER,1992 Summer,1992,Summer,Barcelona,Athletics,Athletics Women's 800 metres,NaN